appName : Identity Server User Portal
theme : org.wso2.carbon.uuf.is.portal.theme.default
menu :
  main :
    Home : {link: "#", icon: "fw-home"}
    Stories :
      Self Sign-up : {link: "user/self-signup"}
      Filling out the default attribute profile : {link: "user/attribute-profile/default-attributes", icon: "fw fw-add"}
      Creating an attribute profile : {link: "user/attribute-profile/new-attributes", icon: "fw fw-add" }
      View Profile: {link: "user/attribute-profile/view-attributes", icon: "fw fw-view"}
      Update Profile: {link: "user/attribute-profile/update-attributes", icon: "fw fw-user"}
      Delete Profile (Tentative): {link: "user/attribute-profile/delete-attributes", icon: "fw fw-delete"}
      Password Update: {link: "user/account/change-password", icon: "fw fw-user"}
errorPages:
  "404": /foundation/error/404
  default: /foundation/error/default